# Generated by Django 5.2.3 on 2025-07-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
