# Generated by Django 5.2.4 on 2025-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
