# Generated by Django 5.2.4 on 2025-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_expensecategory_icon_alter_incomesource_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
